export const ITEM_KIND = {
  COMPONENT: "COMPONENT",
  KIT: "KIT",
} as const;
export type ItemKind = (typeof ITEM_KIND)[keyof typeof ITEM_KIND];

export const SALES_ORDER_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  AWAITING_PROCUREMENT: "AWAITING_PROCUREMENT",
  RESERVED: "RESERVED",
  PICK_READY: "PICK_READY",
  FULFILLED: "FULFILLED",
  SHIPPED: "SHIPPED",
  CANCELLED: "CANCELLED",
} as const;
export type SalesOrderStatus = (typeof SALES_ORDER_STATUS)[keyof typeof SALES_ORDER_STATUS];

export const PROCUREMENT_NEED_STATUS = {
  OPEN: "OPEN",
  ORDERED_FROM_SUPPLIER: "ORDERED_FROM_SUPPLIER",
  RECEIVED_PARTIAL: "RECEIVED_PARTIAL",
  COMPLETE: "COMPLETE",
} as const;
